name: DZ4 Test

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:

      - name : "first"
        uses: actions/checkout@v3
      - name : "second"
        run: nvm clean test
        continue-on-error: true
      - name : "third"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: target/allure-history
      - name : "forth"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}
          PERSONAL_TOKEN: $${{ secrets.GITHUB_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-history
